apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    component: payment
spec:
  containers:
  - name: payment
    image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/payment:1.0.0


---


apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    component: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80