apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    component: shipping
spec:
  containers:
  - name: shipping
    image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/shipping:1.0.0


---


apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    component: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080