apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::581798224530:role/role-for-eks

  
---


apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  serviceAccountName: cart
  containers:
    - name: cart
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/cart:1.0.3
  initContainers:
    - name: ssm-for-parameters
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/aws-params:1.0.6
      args: ["sample:jenkins_user"]



---


apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

