apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    component: catalogue
spec:
  containers:
  - name: catalogue
    image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/catalogue:1.0.0


---


apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080