apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  initContainers:
  - name: init-myservice
    image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/aws-params:1.0.1
    args: [sample:jenkins_user]
  containers:
  - name: frontend
    image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/frontend:1.0.3



---


apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::581798224530:role/ssm-for-eks
spec:
  ServiceAccountName: frontend
