apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  containers:
  - name: frontend
    image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/frontend:1.0.3



---


apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80