apiVersion: v1
kind: Pod
metadata:
  name: schema-load
spec:
  containers:
    - name: schema-load
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/schema-load
      args: [ "first", "second" ]