apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::581798224530:role/role-for-eks

  
---


apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    component: user
spec:
  serviceAccountName: user
  containers:
    - name: user
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/user:1.0.3
      volumeMounts:
      - mountPath: /params
        name: params
  initContainers:
    - name: ssm-for-parameters
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/aws-params:1.0.9
      args: ["sample:jenkins_user"]
      volumeMounts:
      - mountPath: /params
        name: params
  volumes:
  - name: params
    emptyDir:
      sizeLimit: 500Mi


---


apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    component: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

